import { Inter } from "next/font/google";

import { NextAuthProvider } from "src/components/templates/NextAuthProvider";
import { Footer } from "src/components/organisms/footer/Footer";

import "src/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <div className="w-full bg-gray-50">
          <main>
            <NextAuthProvider>{children}</NextAuthProvider>
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
